// Perfect Number Math · 元数据

import type { AlgorithmMeta } from '../../../types.ts';

export const meta: AlgorithmMeta = {
  id: 'perfect-number-math',
  categoryId: 'math',
  title: { zh: '完全数·数学视角', en: 'Perfect Number (Mathematical)' },
  summary: {
    zh: '判定完全数并展示 Euclid-Euler 定理的梅森素数生成式。',
    en: 'Test perfect numbers and show the Euclid-Euler Mersenne-prime form.',
  },
  description: {
    zh: '完全数等于其真因子之和：6 = 1+2+3。Euclid-Euler 定理：偶完全数一一对应梅森素数，形如 2^(p-1)·(2^p - 1)，其中 2^p-1 为素数。本实现给出：(1) 通过求真因子和判定任意 n 是否完全数；(2) 列出由前若干梅森素数生成的偶完全数。判定时间 O(√n)。',
    en: 'A perfect number equals the sum of its proper divisors: 6 = 1+2+3. The Euclid-Euler theorem: even perfect numbers correspond bijectively to Mersenne primes, of the form 2^(p-1)·(2^p - 1) where 2^p-1 is prime. We provide: (1) test any n by summing proper divisors; (2) list even perfect numbers generated by small Mersenne primes. Test time O(√n).',
  },
  tags: ['math', 'number-theory', 'perfect-number', 'mersenne', 'divisors'],
  complexity: { time: 'O(√n)', space: 'O(1)' },
};
