// 高斯混合模型（EM 迭代）· 元数据

import type { AlgorithmMeta } from '../../../types.ts';

export const meta: AlgorithmMeta = {
  id: 'ml-gmm-em-iteration',
  categoryId: 'ml',
  title: { zh: '高斯混合模型（EM 迭代）', en: 'Gaussian Mixture Model (EM Iteration)' },
  summary: {
    zh: '交替执行 E 步（算每个点属于各高斯的责任）与 M 步（更新均值/方差/权重），收敛到 ML 估计。',
    en: 'Alternate E-step (per-point responsibilities for each Gaussian) and M-step (update mean/var/weight) to maximize likelihood.',
  },
  description: {
    zh:
      '高斯混合模型（Gaussian Mixture Model, GMM）用 EM（Expectation-Maximization）算法拟合：' +
      '\n假设数据由 K 个一维高斯分量 N(μ_k, σ_k²) 以混合权重 π_k 生成。' +
      '\n- E 步（求期望）：对每个点 i 与分量 k，计算责任度' +
      '  γ_ik = π_k·N(x_i|μ_k,σ_k²) / Σ_j π_j·N(x_i|μ_j,σ_j²)' +
      '\n- M 步（最大化）：用责任度加权更新参数' +
      '  N_k = Σ_i γ_ik' +
      '  μ_k = Σ_i γ_ik·x_i / N_k' +
      '  σ_k² = Σ_i γ_ik·(x_i−μ_k)² / N_k' +
      '  π_k = N_k / N' +
      '\n- 重复 E/M 直到对数似然收敛' +
      '\n- 优点：软分配（概率）、可建模椭圆簇；缺点：对初始化敏感、可能收敛到局部最优' +
      '\n- 本实现为一维 GMM 教学版（与现有 gmm 区别：聚焦 EM 步骤与责任度可视化）' +
      '\n- 时间 `O(T·n·K)`（T 次迭代），空间 `O(n·K)`。',
    en:
      'Gaussian Mixture Model (GMM) fit via Expectation-Maximization: ' +
      '\nAssume data is generated by K 1-D Gaussian components N(μ_k, σ_k²) with mixing weights π_k. ' +
      '\n- E-step (expectation): for each point i and component k compute the responsibility ' +
      '  γ_ik = π_k·N(x_i|μ_k,σ_k²) / Σ_j π_j·N(x_i|μ_j,σ_j²) ' +
      '\n- M-step (maximize): update parameters weighted by responsibilities ' +
      '  N_k = Σ_i γ_ik ' +
      '  μ_k = Σ_i γ_ik·x_i / N_k ' +
      '  σ_k² = Σ_i γ_ik·(x_i−μ_k)² / N_k ' +
      '  π_k = N_k / N ' +
      '\n- Repeat E/M until log-likelihood converges ' +
      '\n- Pros: soft (probabilistic) assignment, elliptical clusters; Cons: initialization-sensitive, may find local optima ' +
      '\n- This is a 1-D teaching version focused on the EM steps and responsibility visualization ' +
      '\nTime O(T·n·K), space O(n·K).',
  },
  tags: ['ml', 'clustering', 'gmm', 'em-algorithm', 'gaussian'],
  complexity: { time: 'O(T·n·K)', space: 'O(n·K)' },
};
